name: ""
learner: ddpg

buffer_size: 1000000
batch_size: 32

action_selector: "deterministic"
actor: "deterministic"

lr: 0.001
critic_lr: 0.001

expl_noise: 0.1

log_interval: 5000
start_timesteps: 10000

buffer_type: 'transition'