name: sac
learner: sac

buffer_size: 5000
batch_size: 8

action_selector: "squashed_gaussian"
actor: "squashed_gaussian"

lr: 0.0005
critic_lr: 0.0005

hidden_dim: 256

# entropy
pi_entropy: True
ent_coef: 0.2

start_timesteps: 0
log_interval: 500

LOG_STD_MAX: 2
LOG_STD_MIN: -20