env: 'Ant-v2'

batch_size: 32

use_cuda: True
use_tensorboard: True

max_timesteps: 1000000 # stop after running {} timesteps
start_timesteps: 25000  # use random policy till running for {} timesteps
log_interval: 2000 # log and evaluate policy every {} timesteps
test_nepisodes: 24  # number of episodes for testing

tau: 0.005
gamma: 0.99

grad_norm_clip: 10

# whether store these items in the buffer
buf_act_logprob: False
buf_act_onehot: False
